# frozen_string_literal: true

source 'https://rubygems.org'

gem 'base64', '~> 0.2'
gem 'dotenv', '~> 2.8'
gem 'faraday', '~> 2.7'
gem 'json', '~> 2.6'
gem 'logger', '~> 1.5'
gem 'mcp', '~> 0.1'
gem 'puma', '>= 5.0.0'
gem 'rackup', '>= 2.1.0'
gem 'rake', '~> 13.0'

group :development, :test do
  gem 'minitest', '~> 5.18'
  gem 'minitest-reporters', '~> 1.6'
  gem 'mocha', '~> 2.1'
  gem 'pry', '~> 0.14'
  gem 'rubocop', '~> 1.50'
  gem 'shoulda-context', '~> 2.0'
  gem 'webmock', '~> 3.18'
end
